"""account order

Revision ID: 145d31f81ca7
Revises: da893e4de616
Create Date: 2023-12-30 13:23:23.766437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145d31f81ca7'
down_revision = 'da893e4de616'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('order', sa.Integer(), nullable=True))
    op.create_index('acc_order_idx', 'account', ['order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('acc_order_idx', table_name='account')
    op.drop_column('account', 'order')
    # ### end Alembic commands ###
