version: "3.9"

services:

  postgresdb-dev:
    image: postgres:latest
    container_name: postgresdb-dev
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - ../POSTGRES:/var/lib/postgresql/data
    restart: always

  nginx-static:
    build: nginx/
    ports:
      - "8010:80"
    volumes:
      - ../frontend/static/:/www-data
    restart: always